### ISSUE TITLE
Unable to perform successful deploys just after updating SST version

### ISSUE THREAD

**Issue by imjulianeral** [anomalyco/sst#4989] opened 2024-10-28 21:52 UTC
Hello there. I've been facing this issue since 2 weeks ago.

Inicially it was just the SNSTopic subscriber names that collisioned because I need to put custom names to search lambdas quickly when I'm facing downtime.

Then a serius problem happened, the runtime [`provided.al2023`](https://github.com/sst/sst/issues/4960) was not recognized but also it broke my Fargate instance provoking downtime in my staging env. Why? because some loggroups from the fargate's load balancer collissioned for some reason.

But today happened in production without happening in staging.  Also the node.js lambdas code were not deployed.

And I'm not the only one, some other developers are facing similar issues with [S3](https://discordapp.com/channels/983865673656705025/983865673656705028/1300570888336310356).

Maybe the docs need to be updated to perform a successful SST version upgrading without issues.

Please let me know if you need more info of the issues.

**Comment by fwang** [comment] 2024-10-29 13:27
a few different issues are happening here, lemme expand on each:

1. > SNSTopic subscriber names that collisioned because I need to put custom names

Got it. Will fix.

2. > the runtime https://github.com/sst/sst/issues/4960 was not recognized

Is the runtime `provided.al2023` not recognized after the fix in v3.2.49?

3. > some loggroups from the fargate's load balancer collissioned for some reason

Do u recall the name of the log group? Or what the log group name starts with?

You mentioned that the above issues led to downtime. Normally when deploying, SST will try to create the new resources, and only remove the old resources if the new resources are successfully created. So if the new resources fail to create, there shouldn't be downtime as the old resources are still around. Can you elaborate on the downtime, were old resources removed?

**Comment by imjulianeral** [comment] 2024-10-29 15:54
Hello @fwang! Thanks for asking. 

1. Thanks 🙏.

2. The `provided.al2023` runtime is already fixed, the reason of why I mentioned it is because I tought it was important to give context of all the events that occured after I tried to upgrade. Sorry for not being crystal clear on this 😅.

3. I did not rename anything, I just executed `sst upgrade` and then `sst deploy` and it happened. 

About the downtime there are 2 issues:

1. The service task in the ecs cluster failed to update, so the 1 task that was running, wasn't running anymore and the state of the deploy turn into `failed`. So, no resources were removed, updating the service in the AWS console wasn't working but making a second deploy resolved the downtime after 6 minutes of performing it, Idk why it worked but I was in panic and the best thing that come in my mind at that time was to just try again.

2. The node.js runtime Lambdas code were not deployed. My lambdas were having some execution errors saying that the handler function wasn't exposed and checking the code tab in AWS console I just found this:

![image](https://github.com/user-attachments/assets/19e3b3a6-642d-4db1-bdc3-768de48c4a64)

So that's it, if you need more info, please let me know.

**Comment by imjulianeral** [comment] 2024-10-29 16:11
Also, I tried to upgrade from version 3.1.29 to 3.2.62.

**Comment by fwang** [comment] 2024-10-31 16:54
@imjulianeral fixed #1 in v3.2.71.

In v3.2.71, we overloaded a new `topic.subscribe` call that takes a subscriber name as the first argument. ie.
```ts
// deprecated
topic.subscribe({ handler, name })

// use this
topic.subscribe("MySubscriber", { handler, name })
```

To use the new `.subscribe`, you'd need to rename the subscriber function name (for the last time).

^ if u r not ready to make the change, it's okay. The deprecated `.subscribe` function will continue to work.

**Comment by imjulianeral** [comment] 2024-11-08 12:20
Hello @fwang. I've created a [repo](https://github.com/imjulianeral/sst-upgrade-issue) with a minimal reproduction example of the issues described. Please let me know if you have questions.

![image](https://github.com/user-attachments/assets/dad77c83-fc81-41c9-8398-f901e5e1ed70)

**Comment by fwang** [comment] 2024-11-10 20:37
@imjulianeral Thanks for putting it together!

I'm able to reproduce w/ the repo. SST recently moved asset building (ie. function code) from Node to Go. And the behavior for resolving files outside of the SST app was changed, ie. `lambda/` is outside of `sst/`.

We are putting in a fix.

**Comment by fwang** [comment] 2024-11-11 22:46
@thdxr should've pushed out release last night. Can you give the latest version a try?

**Comment by imjulianeral** [comment] 2024-11-13 15:30
I just tested the version `3.3.21`. The lambda code is successfuly deployed now, thanks a lot.

The only remaining issue is the cluster's service which can't describe the target groups just after upgrading for some reason.

**Comment by fwang** [comment] 2024-11-20 14:37
@imjulianeral oh can u do an `sst refresh` and then deploy again?

**Comment by imjulianeral** [comment] 2024-11-20 16:21
OMG it worked. But why this happens? this is because of my dir structure? or version jump is to big? It's mandatory to do this every time I upgrade the sst version?

**Comment by fwang** [comment] 2024-11-28 23:48
We moved how SST packages assets from Node to Go for performance and other improvements. And we didn't handle the case w/ ur dir structure. And that was fixed.

And no, it's not something you need to do on sst upgrades.

**Closed as completed by fwang** 2024-11-28 23:48 UTC
